"""empty message

Revision ID: 77aeaae1224f
Revises: c6900212ec56
Create Date: 2021-10-01 14:48:07.321042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77aeaae1224f'
down_revision = 'c6900212ec56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('product', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'product')
    # ### end Alembic commands ###
