"""empty message

Revision ID: 78bdaae1224g
Revises: 77aeaae1224f
Create Date: 2021-10-01 14:48:07.321042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bdaae1224g'
down_revision = '77aeaae1224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'platform')
    # ### end Alembic commands ###
