"""empty message

Revision ID: c6900212ec56
Revises: f011c050b9ba
Create Date: 2021-07-16 23:48:07.321042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6900212ec56'
down_revision = 'f011c050b9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('report_source', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('team_id', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('team_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'report_source')
    op.drop_column('incident', 'team_id')
    op.drop_column('incident', 'team_name')
    # ### end Alembic commands ###
